### ISSUE TITLE
Magic dependency number in Tutorial #1?

### ISSUE THREAD

**Issue by dsouth** [magomimmo/modern-cljs#141]
I've just completed the first tutorial and so far very nicely done.

However, I think I missed *how* you determined the dependency version for clojurescript. The feedback before it is set was 

```
You're using [lein-cljsbuild "1.0.0"], which is known to work well with ClojureScript 0.0-2014 - *.
```

And in the update edit, you've used ```"0.0-2069"```, but it isn't clear to me how you determined that this was the correct version.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
