### ISSUE TITLE
Error Running lein test: no class def found javax/servlet/http/HttpServletRequest

### ISSUE THREAD

**Issue by mrwizard82d1** [magomimmo/modern-cljs#146]
When completing tutorial 15, I encountered the following error running lein test:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest, compiling:(ring/middleware/multipart_params.clj:39:5)

After some searching, I found the following on the compojure site: https://github.com/weavejester/compojure/issues/98.

As the note suggested, I added an explicit dependency on ring 1.2.1 and resolved the error.

Here's the diff of my project.clj. It includes both the changes indicated in the tutorial and the explicit dependency on ring:

diff --git a/project.clj b/project.clj
index 0d1bbba..7f11013 100644
--- a/project.clj
+++ b/project.clj
@@ -6,6 +6,11 @@
   
   ;; Clojure and ClojureScript source code paths
   :source-paths ["src/clj" "src/cljs" "src/brepl"]
+
+  ;; Unit test paths
+  :test-paths ["test/clj"]
+
+  ;; Project dependencies
   :dependencies [[org.clojure/clojure "1.6.0"]
                  [org.clojure/clojurescript "0.0-2202"]
                  [compojure "1.1.6"]
@@ -16,7 +21,8 @@
                  [org.clojars.magomimmo/shoreleave-remote
                   "0.3.1-SNAPSHOT"]
                  [com.cemerick/valip "0.3.2"]
-                 [enlive "1.1.5"]]
+                 [enlive "1.1.5"]
+                 [ring "1.2.1"]]
 
   ;; Leiningen plugin to help building ClojureScript projects.
   :plugins [[lein-cljsbuild "1.0.3"]
@@ -24,7 +30,9 @@
 
   ;; ClojureScript build configuration
   :cljsbuild {:crossovers
-              [valip.core valip.predicates modern-cljs.login.validators]  
+              [valip.core valip.predicates
+               modern-cljs.login.validators
+               modern-cljs.shopping.validators]
               :builds 
               {:dev
                ;; For development, remove extraneous whitespace and

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
