### ISSUE TITLE
XSS & BREPL

### ISSUE THREAD

**Issue by xcthulhu** [magomimmo/modern-cljs#154]
I was banging my head trying to understand why I couldn't get the BREPL to work, when I finally tried in Safari (on OS X) and got XSS errors.

Can anyone else reproduce or corroborate this?

Anyhow, disabling XSS in a browser does the trick:
http://stackoverflow.com/a/23986416/586893

Should this be mentioned in Tutorial 2?

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
