### ISSUE TITLE
cljsbuild :builds, map vs vector

### ISSUE THREAD

**Issue by stepugnetti** [magomimmo/modern-cljs#175]
Up to tutorial 15 the :builds property for cljsbuild is coded as a vector:
```
  :cljsbuild {:builds [
  {:id ...
   ...}
  {:id ...
   ...}
  ... ] ...}
```
Starting from tutorial 16 the map sysntax is used, without the reader being warned:
```
  :cljsbuild {:builds {
  "id1"
  { ... }
  "id2"
  { ... }
  ... }
```
We should decide which of the two to choose and use it consistently.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
