### ISSUE TITLE
cljs-tutorial doesn't work with emacs C-c C-e

### ISSUE THREAD

**Issue by pcn** [magomimmo/modern-cljs#178]
After starting austin, every form that's evaluated returns nil.  This is the version of the file that I'm using at the moment:

https://github.com/magomimmo/modern-cljs/blob/3f55192202ba998326705d2b853ac85cd091e7fe/cljs-tutorial/project.clj

I'm trying out newer versions of austin and cljs.

**Comment by magomimmo** [comment]
could you please give me more information on which tutorial number are you evaluating?

**Comment by pcn** [comment]
Per the link, I'm having this issue with the cljs-tutorial - the translation of the lt-cljs-tutorial.

**Comment by mcdemarco** [comment]
I also have this problem; everything evaluates to nil in the echo area, although the correct values are shown in the *cider-repl cljs-tutorial* buffer.  Before starting up austin, it echoes correctly up to line 200 (where the js starts).

**Comment by magomimmo** [comment]
Sorry to be so late. I'm in the process of updating the entire series of tutorial At the moment I removed the cljs-tutorial because there are new and more efficient way to run a cljs repl (e.g. cider) to learn cljs without being annoyed with other stuff.
cheers
