### ISSUE TITLE
Two issues immediately preventing me from running the tutorial

### ISSUE THREAD

**Issue by ameliusg** [magomimmo/modern-cljs#180]
Hi, great work on the tutorial. But I immediately got stuck on two issues. First, I'm running the tutorial on a server, not "localhost". Second, my port 9000 was already taken. This is a pity, considering the amount of effort that was (supposedly) put into making this whole tutorial run out of the box.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
