### ISSUE TITLE
Can't eval ClojureScript from cider repl

### ISSUE THREAD

**Issue by bishopmatthew** [magomimmo/modern-cljs#198]
I'm trying to work through cljs-tutorial/README.md but I can't get ClojureScript to eval in the repl. 

OS X 10.9.5
Emacs 24.4.1
Leiningen 2.5.1
```
; CIDER 0.9.0snapshot (package: 20150405.332) (Java 1.7.0_65, Clojure 1.5.1, nREPL 0.2.7)
user> (+ 5 5)
10
user> (cemerick.austin.repls/exec)
Browser-REPL ready @ http://localhost:52297/9373/repl/start
WARNING: Symbol ILookup is not a protocol at line 1153 /Users/matthewbbishop/Projects/clojurescript/modern-cljs/cljs-tutorial/src/cljs/cljs_tutorial/core.cljs
...
WARNING: Symbol IMap is not a protocol at line 1321 /Users/matthewbbishop/Projects/clojurescript/modern-cljs/cljs-tutorial/src/cljs/cljs_tutorial/core.cljs
Type `:cljs/quit` to stop the ClojureScript REPL
nil
cljs.user> (+ 5 5)
```
But the final form never executes for me. Any ideas what could go going on?

**Comment by magomimmo** [comment]
sorry to be so late. i'm in the process of updating the entire series of tutorial. At the moment I removed the cljs-tutorial because there are new and more efficient way to run a cljs repl, even by using the new cider 0.10.0-SNAPSHOT. 
cheers
