### ISSUE TITLE
Tutorials 5 and 6: camelCase binding `theForm` is not idiomatic Clojure

### ISSUE THREAD

**Issue by sumbach** [magomimmo/modern-cljs#210]
In [Tutorial 5](https://github.com/magomimmo/modern-cljs/blob/master/doc/tutorial-05.md) and [Tutorial 6](https://github.com/magomimmo/modern-cljs/blob/master/doc/tutorial-06.md), it would be better to use `the-form` instead of `theForm`.

Idiomatic Clojure typically uses "lisp case" for var and local binding names: https://github.com/bbatsov/clojure-style-guide#naming

**Comment by sumbach** [comment]
@magomimmo This looks like a minor miss as you were transcribing examples from JavaScript to Clojure/ClojureScript.

I'm happy to open a pull request to correct this (minor) issue, but I'm not sure how you handle code+tutorial text changes. Do you have a process for updating the tutorial code as well as the tutorial Markdown text?

**Comment by magomimmo** [comment]
sorry to be so late. I'm in the process of updating the entire series of tutorials. You're absolutely right!
I'll modified it. 
thanks
