### ISSUE TITLE
Fail on `lein cljsbuild once`

### ISSUE THREAD

**Issue by Abdillah** [magomimmo/modern-cljs#212]
In tutorial 1, I got an error like this..
```
$ lein cljsbuild once
'cljsbuild' is not a task. See 'lein help'.
```

I solve it using `$ lein do cljsbuild once`. This not found on any docs except in https://github.com/emezeske/lein-cljsbuild/issues/339 where we should use `do`. 

Please give more info regarding this. As anybody reading it must be a newbie as I am..
Thanks.

**Comment by magomimmo** [comment]
That's very very strange. It never happened to anyone but you. 
have you tried the following? 
git clone https://github.com/magomimmo/modern-cljs.git
cd modern-cljs
git checkout tutorial-01
lein cljsbuild once

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
