### ISSUE TITLE
tutorial 2 =>WARNING: No such namespace: goog.string at line 9 ../.m2/repository/org/clojure/clojurescript/0.0-2197

### ISSUE THREAD

**Issue by Txellenne** [magomimmo/modern-cljs#217]
I got a lot of warning output when evaluating tutorial 2 and cannot get it done successfully, any clue please???
It seems to me it's related to a `cljs compiler` version problem but I got successfully evaluated the **tutorial-1** and basically what you do at **tutorial-2** is to add the `connect.cljs` script to the stack `(../src/cljs/modern_cljs/)`. So I got some dizzy. What I found out, as the guideline  at **tutorial 2** is to write down the file over a clone of **tutorial-1**, is that the `project.clj` file doesn't read same in both of them: 
**tutorial-2** uses `lein-cljsbuil 1.0.3` and declares dependencies on `org.clojure/clojure "1.5.1"` & `org.clojure/clojurescript "0.0-2197"`
and **tutorial-1** rather, calls for the `:plugins lein-cljsbuild "1.0.0"` and got dependencies on `org.clojure/clojure "1.6.0"` & `org.clojure/clojurescript "0.0-2069"`
I would appreciate any help on this..

**Comment by Txellenne** [comment]
`Domina` reads promising but also warns to be still under development..  What about updating this tutorial using e.g. `Enfocus`?? [I promes as soon as I am able to I'll join the nice people who work on this for help on whatsoever] ~~

**Comment by magomimmo** [comment]
Hi, I'm in the process to update the whole series, because of the clojurescript ecosystem evolution from the time I wrote the tutorials. 

At the moment everything should work up to tutorial-04. 

Cheers
mimmo

**Comment by magomimmo** [comment]
Now everything should work up to tutorial-05, aside from few warnings relative to the current cljs release (1.7.145) and domina. those warnings do not hurt.
cheers
