### ISSUE TITLE
Tutorial 05 - Brenton Ashworth's github account doesn't have the "one" repository (anymore?)

### ISSUE THREAD

**Issue by magopian** [magomimmo/modern-cljs#225]
The references to Brenton Ahsworth's `one` repository on github are broken (either it's been renamed, or maybe removed?).

This means that the links https://github.com/magomimmo/modern-cljs/blame/master/doc/tutorial-05.md#L32-L33 and https://github.com/magomimmo/modern-cljs/blame/master/doc/tutorial-05.md#L32-L33 are broken.

**Comment by magomimmo** [comment]
Yes, probably it is no more available. I'll correct tomorrow evening. Thanks.

**Comment by magomimmo** [comment]
Just take into account that I decided to rewrite the entire series using `boot` which, IMHO, it's easier to be used to configure a complete cljs dev environment (very close to figwheel). Be patient....
Cheers

**Comment by magomimmo** [comment]
Hi @magopian, if you are still interested, I already ported 11 tutorials of the series on `boot

**Comment by magomimmo** [comment]
you can start reading them from the `doc/second-edition` directory. I think it will take a couple of weeks more before I decide to publish them as the main docs in the README. 

cheers

**Comment by magopian** [comment]
Hi @magomimmo thanks for keeping me up to date! I am indeed still interested, but didn't have a moment lately to go through them. I still hope to be able to in a couple of weeks hopefully!

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
