### ISSUE TITLE
Tutorial 4: Repl hangs when requiring login

### ISSUE THREAD

**Issue by adsteel** [magomimmo/modern-cljs#233]
In step 5, when requiring modern-cljs.login in the brepl, it does not seem to be required and the repl hangs. I'm new to all of this, so it's hard to trouble shoot.

```
$ lein trampoline cljsbuild repl-listen
Running ClojureScript REPL, listening on port 9000.
Compiling client js ...
Waiting for browser to connect ...
To quit, type: :cljs/quit
cljs.user=> (require '[modern-cljs.login :as m])
# just hangs
```

I got a little further with a different syntax, but not far enough:
```
cljs.user=> (:require [modern-cljs.login :as m])
WARNING: Use of undeclared Var cljs.user/m at line 1 <cljs repl>
nil
cljs.user=> m/validate-form
WARNING: No such namespace: m, could not locate m.cljs, m.cljc, or Closure namespace "" at line 1 <cljs repl>
WARNING: Use of undeclared Var m/validate-form at line 1 <cljs repl>
ReferenceError: m is not defined
	 (NO_SOURCE_FILE)
```

Tutorial snapshot:
![image](https://cloud.githubusercontent.com/assets/4186462/11763174/cf8af52e-a0bd-11e5-8a65-a230c7bd3314.png)

**Comment by adsteel** [comment]
I have made this work by requiring using a different syntax, within the cljs.user namespace.

```clojure
(ns cljs.user
  (:require [modern-cljs.login :as m]))
```

**Comment by magomimmo** [comment]
hi Adam, I have to confess that it's long time from the last time I used `lein trampoline` for connecting a cljs repl with the browser. Moreover I'm in the process of writing the second edition of the modern-cljs series which does not use `lein` anymore. I'm pretty sure you can get a more robust experience with CLJS REPL by using that second edition of the series. I should be able to formally publish in an a couple of week, but you get read the first 14 tutorials (draft) immediately here:

https://github.com/magomimmo/modern-cljs/tree/master/doc/second-edition

HIH

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.

**Comment by adsteel** [comment]
Thanks for your response, I didn't originally catch that I was on the 1st edition vs the updated 2nd. I'll switch over, and thanks for all your work on this!

**Comment by magomimmo** [comment]
You could not catch it, I just switched the master a couple of hours ago :-)..

Take in accoount that the second edition is still in fraft mode….but the code should work, even becasue the boot build tool is much simpler to be used than leinignen/cljsbuild for this kind of stuff.
