### ISSUE TITLE
How about CDN?

### ISSUE THREAD

**Issue by jiyinyiyong** [magomimmo/modern-cljs#235]
In our app we need to put JavaScript on a CDN server with hashes in file names, like Webpack does. Can we do this too with cljsbuild?

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.

**Comment by jiyinyiyong** [comment]
@emezeske

**Comment by emezeske** [comment]
I haven't been an active developer on lein-cljsbuild in some time, but maybe @mneise would know more.

**Comment by mneise** [comment]
@jiyinyiyong So far as I know, ClojureScript or lein-cljsbuild do not provide this functionality.

**Comment by jiyinyiyong** [comment]
Is there any other tool doing  this for ClojureScript?

**Comment by mneise** [comment]
Not that I know of, but then I am also not very familiar with boot-cljs or shadow-build. It might be worth to ask about this in the ClojureScript channel of the clojurians Slack community.

**Comment by magomimmo** [comment]
@jiyinyiyong try to ask on the #boot channel in the clojarians Slack community as well. I'm not aware of such a facilities.
