### ISSUE TITLE
Ch3, 2nd Ed, can't connect browser to bRepl

### ISSUE THREAD

**Issue by adsteel** [magomimmo/modern-cljs#241]
The bRepl was working for me at the end of chapter 2, but at the end of chapter 3, when trying to fire up a bRepl, the folder js/main.out gets deleted.

1. In one terminal I run `boot dev` and wait for the `Elapsed time` message, confirming that the nRepl server has started. At this point `js/main.out/` exists.
2. In a second terminal I run `boot nrepl -c`. This deletes `js/main.out/`.
3. When I try to execute (start-repl) in the second terminal, I get the following error in the first terminal:

```bash
java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: target/js/main.out/cljs_deps.js
```

My versions:

```bash
$ boot -V
#http://boot-clj.com
#Fri Dec 18 15:14:36 MST 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.1
```

**Comment by adsteel** [comment]
I added a boot.properties folder, setting boot version to 2.4.2, and that prevents the `js/main.out` folder from being deleted, but when I try to connect to the bRepl with `(start-repl)`, I get a network error in the browser:

```
Request URL:http://localhost:3000/main.js
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:3000
```

**Comment by adsteel** [comment]
When I use your code, everything works find. When I use your code and bump to boot version 2.5.1, things are still fine. I could not find the difference, but I'm sure it was there.

**Comment by adsteel** [comment]
For what it's worth, when I connect using your code but boot version 2.5.1, I can connect with the bRepl but I see that original error:

```bash
java.nio.file.NoSuchFileException: target/js/main.out/cljs_deps.js
```

**Comment by magomimmo** [comment]
you coul do as follows:

* checkout se-tutorial-02
* code by following the tutorial
* when done git diff with original se-tutorial-03 (i.e. `git diff origin/se-tutorial-03`

HIH

**Comment by magomimmo** [comment]
um, as I said I was hoping that they rigorously follow the semantic version...but the did not...
