### ISSUE TITLE
Something wrong with boot-reload.

### ISSUE THREAD

**Issue by philoskim** [magomimmo/modern-cljs#244]
When I run 'boot dev' command in se-tutorial-03, I encountered the following exception.
I guess something is wrong with the boot-reload.
  
modern-cljs $ git checkout se-tutorial-03
Your branch is up-to-date with 'origin/se-tutorial-03'.

modern-cljs (se-tutorial-03)$ boot dev
             clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
    data: {:file "/tmp/boot.user4849423334931571039.clj", :line 13}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
         java.lang.NoClassDefFoundError: clojure/lang/IFn
       java.lang.ClassNotFoundException: clojure.lang.IFn
                                             ...                                        
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...                                        
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...                                        
adzerk.boot-reload.server/eval54/loading--auto--                        server.clj:    1
                adzerk.boot-reload.server/eval54                        server.clj:    1
                                             ...                                        
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...                                        
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...                                        
                           boot.pod/eval-fn-call                           pod.clj:  182
                               boot.pod/call-in*                           pod.clj:  191
                                             ...                                        
                               boot.pod/call-in*                           pod.clj:  194
                 adzerk.boot-reload/start-server                   boot_reload.clj:   27
                   adzerk.boot-reload/eval384/fn                   boot_reload.clj:  104
                                             ...                                        
                            boot.user/eval525/fn  boot.user4849423334931571039.clj:    9
                                             ...                                        
                              clojure.core/apply                          core.clj:  630
                       boot.core/construct-tasks                          core.clj:  684
                                             ...                                        
                              clojure.core/apply                          core.clj:  630
                               boot.core/boot/fn                          core.clj:  712
             clojure.core/binding-conveyor-fn/fn                          core.clj: 1916

**Comment by magomimmo** [comment]
unh, very strange. I just did the following:

```bash
git clone https://github.com/magomimmo/modern-cljs.git
cd modern-cljs
git checkout se-tutorial-03
boot dev
Starting reload server on ws://localhost:53759
Writing boot_reload.cljs...
Writing boot_cljs_repl.cljs...
2015-12-22 09:57:30.914:INFO::clojure-agent-send-off-pool-0: Logging initialized @9248ms
2015-12-22 09:57:30.977:INFO:oejs.Server:clojure-agent-send-off-pool-0: jetty-9.2.10.v20150310
2015-12-22 09:57:30.999:INFO:oejs.ServerConnector:clojure-agent-send-off-pool-0: Started ServerConnector@71ac2c82{HTTP/1.1}{0.0.0.0:3000}
2015-12-22 09:57:31.000:INFO:oejs.Server:clojure-agent-send-off-pool-0: Started @9334ms
Started Jetty on http://localhost:3000

Starting file watcher (CTRL-C to quit)...

Adding :require adzerk.boot-reload to main.cljs.edn...
nREPL server started on port 53760 on host 127.0.0.1 - nrepl://127.0.0.1:53760
Adding :require adzerk.boot-cljs-repl to main.cljs.edn...
Compiling ClojureScript...
• js/main.js
Elapsed time: 17.605 sec
```

and everything went as expected. 

Are you sure you're using the boot release `2.4.2`?

```bash
boot -V
#https://github.com/boot-clj/boot
#Tue Dec 22 09:59:19 CET 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
#App version: 2.4.2
```

I never tested the boot `2.5.1` release which has been published few days ago.

**Comment by magomimmo** [comment]
Sometimes `boot` gets confused with the `boot -u` command which upgrades boot iteself. When this happens I do the following:

* delete the `~/.boot/cache` directory
* delete the `~/.m2/repository` directory

and start again boot. It will download everything from scratch.... 

```bash
git clone https://github.com/magomimmo/modern-cljs.git
cd modern-cljs
git checkout se-tutorial-03
boot dev
```

The `se-tutorial-03` already contains the `boot.properties` file:

```bash
#https://github.com/boot-clj/boot
#Sun Nov 01 16:34:27 CET 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
```

**Comment by philoskim** [comment]
I followed your instruction, so I deleted ~/.boot and ~/.m2 directory but unfortunately the same exception happened!

MY OS: Ubuntu 16.04

$ boot
Downloading https://github.com/boot-clj/boot/releases/download/2.3.0/boot.sh...done.
Running for the first time: updating to latest version.
Retrieving boot-2.5.2.jar from https://clojars.org/repo/
Retrieving clojure-1.7.0.jar from https://repo1.maven.org/maven2/
#https://github.com/boot-clj/boot
#Tue Dec 22 18:48:40 KST 2015
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.2
#App version: 2.3.0
Retrieving dynapath-0.2.3.jar from https://clojars.org/repo/
Retrieving pod-2.5.2.jar from https://clojars.org/repo/
Retrieving shimdandy-impl-1.2.0.jar from https://repo1.maven.org/maven2/
Retrieving core-2.5.2.jar from https://clojars.org/repo/
Retrieving worker-2.5.2.jar from https://clojars.org/repo/
Retrieving aether-2.5.2.jar from https://clojars.org/repo/
Retrieving parsley-0.9.3.jar from https://clojars.org/repo/
Retrieving cd-client-0.3.6.jar from https://clojars.org/repo/
......

$ git clone https://github.com/magomimmo/modern-cljs.git
Cloning into 'modern-cljs'...
remote: Counting objects: 7342, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 7342 (delta 96), reused 0 (delta 0), pack-reused 7176
Receiving objects: 100% (7342/7342), 5.26 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (3730/3730), done.
Checking connectivity... done.

$ cd modern-cljs/
modern-cljs (master)$ git checkout se-tutorial-03
Branch se-tutorial-03 set up to track remote branch se-tutorial-03 from origin.
Switched to a new branch 'se-tutorial-03'

modern-cljs (se-tutorial-03)$ boot dev
Downloading https://github.com/boot-clj/boot/releases/download/2.4.2/boot.jar...done.
Retrieving pod-2.4.2.jar from https://clojars.org/repo/
Retrieving core-2.4.2.jar from https://clojars.org/repo/
Retrieving clj-pgp-0.5.4.jar from https://clojars.org/repo/
Retrieving primitive-math-0.1.3.jar from https://clojars.org/repo/
Retrieving worker-2.4.2.jar from https://clojars.org/repo/
Retrieving byte-streams-0.1.13.jar from https://clojars.org/repo/
Retrieving aether-2.4.2.jar from https://clojars.org/repo/
Retrieving clj-tuple-0.1.5.jar from https://clojars.org/repo/
Retrieving potemkin-0.3.9.jar from https://clojars.org/repo/
Retrieving riddley-0.1.7.jar from https://clojars.org/repo/
Retrieving bcpg-jdk15on-1.51.jar from https://repo1.maven.org/maven2/
Retrieving bcprov-jdk15on-1.51.jar from https://repo1.maven.org/maven2/
Retrieving boot-reload-0.4.2.jar from https://clojars.org/repo/
Retrieving boot-http-0.7.0.jar from https://clojars.org/repo/
Retrieving boot-cljs-1.7.170-3.jar from https://clojars.org/repo/
Retrieving weasel-0.7.0.jar from https://clojars.org/repo/
Retrieving http-kit-2.1.18.jar from https://clojars.org/repo/
Retrieving boot-cljs-repl-0.3.0.jar from https://clojars.org/repo/
Retrieving piggieback-0.2.1.jar from https://clojars.org/repo/
Retrieving clojurescript-1.7.170.jar from https://repo1.maven.org/maven2/
Retrieving data.json-0.2.6.jar from https://repo1.maven.org/maven2/
Retrieving closure-compiler-v20151015.jar from https://repo1.maven.org/maven2/
Retrieving google-closure-library-third-party-0.0-20151016-61277aea.jar from https://repo1.maven.org/maven2/
Retrieving google-closure-library-0.0-20151016-61277aea.jar from https://repo1.maven.org/maven2/
Retrieving rhino-1.7R5.jar from https://repo1.maven.org/maven2/
Retrieving tools.reader-0.10.0-alpha3.jar from https://repo1.maven.org/maven2/
Retrieving tools.nrepl-0.2.12.jar from https://repo1.maven.org/maven2/
Retrieving ring-codec-1.0.0.jar from https://clojars.org/repo/
Retrieving ring-core-1.4.0.jar from https://clojars.org/repo/
Retrieving crypto-equality-1.0.0.jar from https://clojars.org/repo/
Retrieving crypto-random-1.2.0.jar from https://clojars.org/repo/
Retrieving ring-devel-1.4.0.jar from https://clojars.org/repo/
Retrieving clj-time-0.9.0.jar from https://clojars.org/repo/
Retrieving clj-stacktrace-0.2.8.jar from https://clojars.org/repo/
Retrieving ns-tracker-0.3.0.jar from https://clojars.org/repo/
Retrieving hiccup-1.0.5.jar from https://clojars.org/repo/
Retrieving ring-servlet-1.4.0.jar from https://clojars.org/repo/
Retrieving ring-jetty-adapter-1.4.0.jar from https://clojars.org/repo/
Retrieving commons-io-2.4.jar from https://repo1.maven.org/maven2/
Retrieving commons-codec-1.6.jar from https://repo1.maven.org/maven2/
Retrieving joda-time-2.6.jar from https://repo1.maven.org/maven2/
Retrieving commons-fileupload-1.3.1.jar from https://repo1.maven.org/maven2/
Retrieving tools.namespace-0.2.10.jar from https://repo1.maven.org/maven2/
Retrieving java.classpath-0.2.2.jar from https://repo1.maven.org/maven2/
Retrieving jetty-server-9.2.10.v20150310.jar from https://repo1.maven.org/maven2/
Retrieving javax.servlet-api-3.1.0.jar from https://repo1.maven.org/maven2/
Retrieving jetty-http-9.2.10.v20150310.jar from https://repo1.maven.org/maven2/
Retrieving jetty-util-9.2.10.v20150310.jar from https://repo1.maven.org/maven2/
Retrieving jetty-io-9.2.10.v20150310.jar from https://repo1.maven.org/maven2/
             clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
    data: {:file "/tmp/boot.user394168445631395046.clj", :line 13}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
         java.lang.NoClassDefFoundError: clojure/lang/IFn
       java.lang.ClassNotFoundException: clojure.lang.IFn
                                             ...                                       
                            clojure.core/load/fn                         core.clj: 5866
                               clojure.core/load                         core.clj: 5865
                                             ...                                       
                           clojure.core/load-one                         core.clj: 5671
                        clojure.core/load-lib/fn                         core.clj: 5711
                           clojure.core/load-lib                         core.clj: 5710
                                             ...                                       
                              clojure.core/apply                         core.clj:  632
                          clojure.core/load-libs                         core.clj: 5749
                                             ...                                       
                              clojure.core/apply                         core.clj:  632
                            clojure.core/require                         core.clj: 5832
                                             ...                                       
adzerk.boot-reload.server/eval54/loading--auto--                       server.clj:    1
                adzerk.boot-reload.server/eval54                       server.clj:    1
                                             ...                                       
                            clojure.core/load/fn                         core.clj: 5866
                               clojure.core/load                         core.clj: 5865
                                             ...                                       
                           clojure.core/load-one                         core.clj: 5671
                        clojure.core/load-lib/fn                         core.clj: 5711
                           clojure.core/load-lib                         core.clj: 5710
                                             ...                                       
                              clojure.core/apply                         core.clj:  632
                          clojure.core/load-libs                         core.clj: 5749
                                             ...                                       
                              clojure.core/apply                         core.clj:  632
                            clojure.core/require                         core.clj: 5832
                                             ...                                       
                           boot.pod/eval-fn-call                          pod.clj:  182
                               boot.pod/call-in*                          pod.clj:  191
                                             ...                                       
                               boot.pod/call-in*                          pod.clj:  194
                 adzerk.boot-reload/start-server                  boot_reload.clj:   27
                   adzerk.boot-reload/eval384/fn                  boot_reload.clj:  104
                                             ...                                       
                            boot.user/eval525/fn  boot.user394168445631395046.clj:    9
                                             ...                                       
                              clojure.core/apply                         core.clj:  630
                       boot.core/construct-tasks                         core.clj:  684
                                             ...                                       
                              clojure.core/apply                         core.clj:  630
                               boot.core/boot/fn                         core.clj:  712
             clojure.core/binding-conveyor-fn/fn                         core.clj: 1916
                                             ...                      
modern-cljs (se-tutorial-03)$ boot -V
#https://github.com/boot-clj/boot
#Tue Dec 22 19:00:01 KST 2015
BOOT_JVM_OPTIONS=-client -XX\:+TieredCompilation -XX\:TieredStopAtLevel\=1 -Xverify\:none
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
#App version: 2.4.2

**Comment by magomimmo** [comment]
could please try without. 
`BOOT_JVM_OPTIONS=-client -XX\:+TieredCompilation -XX\:TieredStopAtLevel\=1 -Xverify\:none`

**Comment by magomimmo** [comment]
perhaps has something to do with this same error:

https://github.com/martinklepsch/tenzing/issues/44

He suggested to build from source master....

**Comment by philoskim** [comment]
I tried without BOOT_JVM_OPTIONS like this but failed again.

```
modern-cljs (se-tutorial-03)$ boot -V
#https://github.com/boot-clj/boot
#Tue Dec 22 20:32:25 KST 2015
BOOT_JVM_OPTIONS=-client -XX\:+TieredCompilation -XX\:TieredStopAtLevel\=1 -Xverify\:none
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
#App version: 2.4.2

modern-cljs (se-tutorial-03)$ export BOOT_JVM_OPTIONS=

modern-cljs (se-tutorial-03)$ boot -V
#https://github.com/boot-clj/boot
#Tue Dec 22 20:32:59 KST 2015
BOOT_JVM_OPTIONS=
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
#App version: 2.4.2

modern-cljs (se-tutorial-03)$ boot dev
             clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
    data: {:file "/tmp/boot.user3425094363105172645.clj", :line 13}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
         java.lang.NoClassDefFoundError: clojure/lang/IFn
       java.lang.ClassNotFoundException: clojure.lang.IFn
                                             ...                                        
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...                                        
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...                                        
adzerk.boot-reload.server/eval54/loading--auto--                        server.clj:    1
                adzerk.boot-reload.server/eval54                        server.clj:    1
                                             ...                                        
                            clojure.core/load/fn                          core.clj: 5866
                               clojure.core/load                          core.clj: 5865
                                             ...                                        
                           clojure.core/load-one                          core.clj: 5671
                        clojure.core/load-lib/fn                          core.clj: 5711
                           clojure.core/load-lib                          core.clj: 5710
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                          clojure.core/load-libs                          core.clj: 5749
                                             ...                                        
                              clojure.core/apply                          core.clj:  632
                            clojure.core/require                          core.clj: 5832
                                             ...                                        
                           boot.pod/eval-fn-call                           pod.clj:  182
                               boot.pod/call-in*                           pod.clj:  191
                                             ...                                        
                               boot.pod/call-in*                           pod.clj:  194
                 adzerk.boot-reload/start-server                   boot_reload.clj:   27
                   adzerk.boot-reload/eval384/fn                   boot_reload.clj:  104
                                             ...                                        
                            boot.user/eval525/fn  boot.user3425094363105172645.clj:    9
                                             ...                                        
                              clojure.core/apply                          core.clj:  630
                       boot.core/construct-tasks                          core.clj:  684
                                             ...                                        
                              clojure.core/apply                          core.clj:  630
                               boot.core/boot/fn                          core.clj:  712
             clojure.core/binding-conveyor-fn/fn                          core.clj: 1916
                                             ...                                        
```

**Comment by magomimmo** [comment]
have you tried with the above suggestion to compile from source the `.2.4.2` release. I would also remove the `BOOT_JVM_OPTIONS` from `~/.boot/boot.properties` instead of exporting the voi value. At the moment I do not have an available Ubuntu OS to help you more.

**Comment by philoskim** [comment]
I tried with the above suggestion to compile from source the .2.4.2 release but failed yet again. Thank you very much anyway!

**Comment by magomimmo** [comment]
I found a collegue with ubuntu 14.04. It worked like a cham. Have you tried the tasks one by one. It seems to be a problem affecting your configuration

**Comment by magomimmo** [comment]
I/m closing the issue because it does not depends on the code of the project.

**Comment by philoskim** [comment]
I found out why I had failed in trying out 'boot dev' command in se-tutorial-03.
The reason is that my boot.sh (renamed boot) in linux was too old (version 2.3.0, not 2.4.2).
So I downloaded the latest version of boot.sh, retried and everything is fine as expected.
Thanks a lot for guiding me to the right path to solve the problem!

**Comment by magomimmo** [comment]
Oh, that’s good! I probably have to mention it in the tutorial.
mimmo

**Comment by sova** [comment]
Hello, I have the same issue using a +rum template, I have used the one-liner to curl boot.sh and chmod... but to no avail.

> vas$ boot -V
> #http://boot-clj.com
> #Sat Apr 21 11:17:29 AEST 2018
> BOOT_CLOJURE_NAME=org.clojure/clojure
> BOOT_CLOJURE_VERSION=1.8.0
> BOOT_VERSION=2.6.0
> vasoeleresence2:nonfo vas$ boot dev
> Writing boot_cljs_repl.cljs...
>              clojure.lang.ExceptionInfo: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
>     data: {:file
>            "/var/folders/qc/zrv4w6ds5yq3lrj24703h18r0000gp/T/boot.user7152719098901952531.clj",
>            :line 21}
> clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: clojure/lang/IFn, compiling:(org/httpkit/server.clj:23:11)
>          java.lang.NoClassDefFoundError: clojure/lang/IFn
>        java.lang.ClassNotFoundException: clojure.lang.IFn
>                                              ...
>                             clojure.core/load/fn                          core.clj: 5893
>                   clojure.core/load/invokeStatic                          core.clj: 5892
>                                clojure.core/load                          core.clj: 5876
>                                              ...
>               clojure.core/load-one/invokeStatic                          core.clj: 5697
>                            clojure.core/load-one                          core.clj: 5692
>                         clojure.core/load-lib/fn                          core.clj: 5737
>               clojure.core/load-lib/invokeStatic                          core.clj: 5736
>                            clojure.core/load-lib                          core.clj: 5717
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  648
>              clojure.core/load-libs/invokeStatic                          core.clj: 5774
>                           clojure.core/load-libs                          core.clj: 5758
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  648
>                clojure.core/require/invokeStatic                          core.clj: 5796
>                             clojure.core/require                          core.clj: 5796
>                                              ...
> adzerk.boot-reload.server/eval56/loading--auto--                        server.clj:    1
>    adzerk.boot-reload.server/eval56/invokeStatic                        server.clj:    1
>                 adzerk.boot-reload.server/eval56                        server.clj:    1
>                                              ...
>                             clojure.core/load/fn                          core.clj: 5893
>                   clojure.core/load/invokeStatic                          core.clj: 5892
>                                clojure.core/load                          core.clj: 5876
>                                              ...
>               clojure.core/load-one/invokeStatic                          core.clj: 5697
>                            clojure.core/load-one                          core.clj: 5692
>                         clojure.core/load-lib/fn                          core.clj: 5737
>               clojure.core/load-lib/invokeStatic                          core.clj: 5736
>                            clojure.core/load-lib                          core.clj: 5717
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  648
>              clojure.core/load-libs/invokeStatic                          core.clj: 5774
>                           clojure.core/load-libs                          core.clj: 5758
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  648
>                clojure.core/require/invokeStatic                          core.clj: 5796
>                             clojure.core/require                          core.clj: 5796
>                                              ...
>                            boot.pod/eval-fn-call                           pod.clj:  326
>                                boot.pod/call-in*                           pod.clj:  379
>                                              ...
>                                boot.pod/call-in*                           pod.clj:  382
>     adzerk.boot-reload/start-server/invokeStatic                   boot_reload.clj:   34
>                  adzerk.boot-reload/start-server                   boot_reload.clj:   33
>                    adzerk.boot-reload/eval521/fn                   boot_reload.clj:  128
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  646
>                               clojure.core/apply                          core.clj:  641
>                       boot.user/eval760/fn/fn/fn  boot.user7152719098901952531.clj:   15
>                                              ...
>                             boot.user/eval689/fn  boot.user7152719098901952531.clj:   11
>                                              ...
>                             boot.user/eval812/fn  boot.user7152719098901952531.clj:   17
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  646
>                               clojure.core/apply                          core.clj:  641
>                        boot.core/construct-tasks                          core.clj:  911
>                                              ...
>                  clojure.core/apply/invokeStatic                          core.clj:  646
>                               clojure.core/apply                          core.clj:  641
>                                boot.core/boot/fn                          core.clj:  949
>              clojure.core/binding-conveyor-fn/fn                          core.clj: 1938
>                                              ...


Removing the (reload) line fixes the httpkit error but obviously disables the hot-reloading of edited files.
