### ISSUE TITLE
Note 3 in Tutorial 05 might be too implicit

### ISSUE THREAD

**Issue by groakat** [magomimmo/modern-cljs#252]
Hi,

I had fun so far following the tutorial. I really love it. Everything worked very smooth until I got struggling a bit to interpret Note 3 in tutorial 05.

https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-05.md#brepling-with-the-login-form

It would be clearer to state it as an explicit instruction, like "place the following require into `login.cljs`". 

I know it is implicitly stated in `(ns modern-cljs.login ...`, but if you are following the tutorial after work and you are not too familiar with everything, yet it is not immediately obvious what one has to do.

**Comment by magomimmo** [comment]
Yep. you're right....I'm going to sleep now. If you want you can make a PR with a better phrasing. Thanks for the help.
