### ISSUE TITLE
Mention configuring BOOT_JVM_OPTIONS

### ISSUE THREAD

**Issue by marcb** [magomimmo/modern-cljs#255]
As part of getting the Second tutorial working it might be worth mentioning https://github.com/boot-clj/boot/wiki/JVM-Options#permgen-errors

e.g. on my Mac I need to set the following to get the boot web server running...
export BOOT_JVM_OPTIONS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx2g -XX:MaxPermSize=128m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"

**Comment by magomimmo** [comment]
Thanks for the suggestion Marc. Probably that mention should go in the very first tutorial.

**Comment by magomimmo** [comment]
done. thanks for the suggestion. https://github.com/magomimmo/modern-cljs/commit/a75932b7859b1a8e8cda176d8a9fc88a051c25b2#diff-d2d009784fb232c8c5b303c7670b3e3fR19
