### ISSUE TITLE
Tutorial 3 - Defaults Overwriting

### ISSUE THREAD

**Issue by neilwashere** [magomimmo/modern-cljs#258]
When following the command to issue `boot -vv cljs` the output doesn't get written to the expected target directory. I checked my settings a few times and the behaviour was consistent. When I issued `boot -vv cljs target` (addition of just 'target') things worked as expected.

Clearly this could be something specific to my setup but I thought I'd raise it in case this was a typo in the tutorial. Let me know if you would like more details.

**Comment by magomimmo** [comment]
you're right. the `boot -vv cljs` command has not be updated to `boot -vv cljs target` when I updated `boot` release from `2.4.2` to `2.5.5`. Thanks. It now requires `target` task if you want to see the effect in the target directory. Thanks for that!

**Comment by magomimmo** [comment]
I update the tutorial...thanks again.
