### ISSUE TITLE
Suggestion: mention zsh in tutorial-1

### ISSUE THREAD

**Issue by gigafone** [magomimmo/modern-cljs#259]
From [tutorial-1](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-01.md)...

This command does not work in Bash:

```
mkdir -p modern-cljs/{src/cljs/modern_cljs,html}
```

Since this seems to be an introductory tutorial (and many people still use bash), I'd suggest directly mentioning that [zsh](http://www.zsh.org/) is required for that command.

**Comment by magomimmo** [comment]
On which operating system did you try the above command?

On Mac OS X it works correctly on a bash shell:

```bash
$ mkdir -p modern-cljs/{src/cljs/modern_cljs,html}
$ tree
.
└── modern-cljs
    ├── html
    └── src
        └── cljs
            └── modern_cljs

5 directories, 0 files
$
```

At the moment I do not have a `GNU/Linux` to test it. I'll do it tomorrow morning and let you know the result.

**Comment by gigafone** [comment]
My mistake. You are correct. I think I must have accidentally used a backward instead of forward slash, creating chaos.
