### ISSUE TITLE
Class cast exception with "AJAXified" calculator - tutorial 9

### ISSUE THREAD

**Issue by rssole** [magomimmo/modern-cljs#275]
Hi, I have followed this tutorial, however, I am getting 
2016-03-10 00:35:19.018:WARN:oejs.HttpChannel:qtp1572783528-35: /_shoreleave
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number

Perhaps some String -> Number conversion is missing in server-side rpc handler?
(e.g. introducing Float/parseFloat in server side remote handler is giving expected behavior - 
if we put aside debate on precision)

Moreover, shoreleave.remotes.macros has been required in tutorial but remain
unused (if I've followed everything correctly). Is there actual purpose it has been
required for or that is for some later tutorials?

Thanks in advance...

**Comment by magomimmo** [comment]
I'll take a look in the weekend. In the mean time did you try the following:
```bash
git clone https://github.com/magomimmo/modern-cljs.git
cd modern-cljs
git checkout se-tutorial-09
```

and do a `diff` with your code base?

Cheers

**Comment by rssole** [comment]
Sure, sure, I planned to do so anyway just didn't grab the moment.
Will, let you know as soon as I do.

**Comment by magomimmo** [comment]
:-)

**Comment by rssole** [comment]
Hm, well, I apologize for an inconvenience, I did comparison and there weren't significant differences apart my wrapping reading values with number parsing.

However, now I reverted to original option, and it works... I can't really tell what was an issue as I am
not able to reproduce it.

Sorry again and please feel free to delete this thread.

**Comment by magomimmo** [comment]
no problem at all.
