### ISSUE TITLE
Unexpected results tutorial 13 Let's Code section

### ISSUE THREAD

**Issue by learningcljs** [magomimmo/modern-cljs#318]
I have been working through tutorial 13 and am not getting this expected results:
> You should see the Shopping Calculator page showing the default field values again and again each time you press the `Calculate` button, no matter what you typed in the value boxes of the fields.

When I put quantity 1 and unit price 1.00 and click calculate I end up at http://localhost:3000/shopping with the result of:
> You entered: 1 1.00 0.0 and 0.00.

But when I change the quantity to 2 and press calculate I end up at http://localhost:3000/shopping with the result of:
> You entered: 2 1.00 0.0 and 0.00.

The last place where I get the expected result is:
> You should now see the Ajax version of the Shopping Calculator working as expected.

**Comment by magomimmo** [comment]
I did not had the time to review this PR https://github.com/magomimmo/modern-cljs/pull/273 which probably fixes the above bug. I'll have an hour tomorrow to get into it. Couls you please eventually verify if the PR solve your problem? Thanks!

**Comment by magomimmo** [comment]
It seems that the #273 PR fixed the bug. Could you please test it from your side? Thanks so much.

**Comment by learningcljs** [comment]
Pull request #273 has fixed this issue.
