### ISSUE TITLE
Chromium error message tutorial 13 Select and transform section

### ISSUE THREAD

**Issue by learningcljs** [magomimmo/modern-cljs#319]
With `Chromium` I am getting an error when I try to do:
> Reload the shopping URI and change the values of the input fields of the Shopping Calculator form.

As soon as I load <http://localhost:3000/shopping.html> with `Chromium` I get this error message:

```
HTTP ERROR: 500

Problem accessing /shopping.html. Reason:
    java.lang.NullPointerException: HTML resource not found., compiling:(shopping.clj:4:1)

Powered by Jetty://
```

I do not get this error with `Iceweasel`.

**Comment by magomimmo** [comment]
there are few problems caused by cut & paste the code from the first edition (the one based on leiningen and cljsbuild plugin). there is a PR that seems to fix those problems. I'm going to test it before tomorrow afternoon.

**Comment by learningcljs** [comment]
Pull request #273 has fixed this issue.
