### ISSUE TITLE
Searching for and selecting CLJ/CLJS dependencies

### ISSUE THREAD

**Issue by learningcljs** [magomimmo/modern-cljs#342]
It would be helpful to have a small appendix piece that covers searching for and selecting CLJ/CLJS dependencies for a project.  What are suggestions on how to do this?

**Comment by magomimmo** [comment]
I do not understand what you exactly mean. Something like:

```bash
git checkout se-tutorial-16
boot show -d
```

**Comment by learningcljs** [comment]
Let's take the example of someone wanting to use CLJS with Node.js.  They want a library to include as a dependency that provides a functional, idiomatic Clojure interface for Node.js

Or it could be that they are looking for a framework for writing SPAs in CLJS.  Reagent could do this but it does not come up in this tutorial series.

What are some suggestions for searching out libraries or frameworks?

What are some suggestions for narrowing down the options and selecting one to include in a project?

In this tutorial series things like `domina` or `valip` are presented as dependency to go with.  It would be good to include a small appendix piece to help people new to the CLJ/CLJS ecosystem which could help them get started with their own searches.

**Comment by magomimmo** [comment]
do you mean something lie this?

http://www.clojure-toolbox.com/

**Comment by learningcljs** [comment]
Yes that is a good resource for someone looking for CLJ/CLJS libraries and tools.

**Comment by learningcljs** [comment]
I think that pull request #355 is sufficient to close this issue.
