### ISSUE TITLE
Problems with Tutorial 2

### ISSUE THREAD

**Issue by doubleagent** [magomimmo/modern-cljs#392]
The tutorial tells me to run this command `boot serve -d target watch cljs target -d target`

It appears to work with some exceptions.

Emacs is writing `src/cljs/modern-cljs/.#core.cljs` and one of the boot tasks is trying to compile it.  Can I instruct boot to ignore hidden files?

cljs logs compilation to the terminal but the generated javascript never changes..  Is there a problem with this on Windows?

Is boot still a better option than Leiningen?  Lein looked really complicated for cljs but I haven't experienced these kinds of problems with it when working with Clojure in the past.  This is my first foray into cljs, though.

**Comment by magomimmo** [comment]
Have you tried the following?

```bash
git clone https://github.com/magomimmo/modern-cljs.git
cd modern-cljs
git checkout se-tutorial-02
```

Regarding Windows I do not have one for testing it. It is said that if you do not have at least Windows 10, boot could have some problem.

**Comment by doubleagent** [comment]
I'm currently on Windows 10.

I'm not entirely through part 2 of the tutorial yet.  My understanding is that if I were to checkout se-tutorial-02, I would have to work backward and remove code in order to try again.

**Comment by doubleagent** [comment]
Disabling Emacs lock files appears to resolve both issues. `(setq create-lockfiles nil)`

**Comment by magomimmo** [comment]
:-)
