### ISSUE TITLE
Provide better documentation for Emacs Cider cider/cider-nrepl version mismatch

### ISSUE THREAD

**Issue by bigos** [magomimmo/modern-cljs#420]
At the moment the situation is very confusing.

"WARNING: CIDER's version (X.X.X) does not match cider-nrepl's version (nil). Things will break!”.

On one hand, https://github.com/boot-clj/boot/wiki/Cider-REPL suggests one solution. 
On the other hand, the link to documentation that appears next to the error in REPL points to http://cider.readthedocs.io/en/latest/installation/#ciders-nrepl-middleware which suggests a slightly different solution. None of them will work with the current cider version. Can you provide a solution to this problem somewhere? 

Because new users are your target audience. I think you need to add a section about troubleshooting and solving this problem.

**Comment by bigos** [comment]
Solution number 3!
https://github.com/clojure-emacs/cider-nrepl

**Comment by magomimmo** [comment]
This series of tutorials is agnostic regarding editor/IDE, even if In the past I accepted a PR linking documentation about using emacs/CIDER. I also suggested **to not make the learning path more complicated** by using an editor/IDE the reader don't already know. The reader can follow the entire series with any editor/IDE supporting clojure/clojurescript syntax (i.e. emacs, atom, vscode, vim, cursive, light table, etc.) even if the editor/IDE does not offer a CLJ/CLJS REPL integration.

**Comment by bigos** [comment]
I understand your point. Where do you suggest I should raise the issue?

**Comment by magomimmo** [comment]
the easiest way to configure emacs/cider is to follow this guide: https://github.com/flyingmachine/emacs-for-clojure#upgrading

But take into account that there is regression bug I fixed in a PR (which is still to be approved), but it solves the issue:

https://github.com/flyingmachine/emacs-for-clojure/pull/29/commits/094bd25edffbf581ab9fab8b033399d5bad06ae1

HIH

**Comment by bigos** [comment]
For Emacs configuration, I use Prelude, which was written by the author of Cider. I have correctly configured this part. I guess the problem lies with boot configuration specific to my environment. Looks like my issue report was raised in the wrong place.
