### ISSUE TITLE
Tutorial 4- second edition, confusing information related to login.js

### ISSUE THREAD

**Issue by bigos** [magomimmo/modern-cljs#421]
In the tutorial 4, section Corting to ClojureScript:
https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-04.md#porting-to-clojurescript

you tell me to:

> update the src attribute of the <script> tag from "js/login.js" to "js/main.js" to link the JS file generated by the CLJS compiler.

Then after Launching the Immediate Feedback Development Environment (IFDE) you discuss behavior of the original login.js code. However, there's no clear information what to do with the code. You say

> Let's start from the validateForm() function:

but it is not clear if I'm supposed to copy the file from Downloads or is it a thought experiment?

**Comment by magomimmo** [comment]
After you launch the IFDE you only have to follow the subsequent bREPL session.

**Comment by bigos** [comment]
The mystery was solved few pages below. Perhaps someone could suggest better wording.
current wording:

> It's now time to start experimenting with CLJS at the bREPL by trying to emulate the behavior of the original login.js code. Let's start from the validateForm() function:

my suggestion:
> It's now time to start experimenting with CLJS at the bREPL by trying to emulate the behavior of the original login.js code. Before we start lets consider example validateForm() function:

**Comment by magomimmo** [comment]
PR are very welcome :-)

**Comment by magomimmo** [comment]
Now that you reworded the paragraph, may we close this issue?
