### ISSUE TITLE
Tutorial 2: out directory not explained

### ISSUE THREAD

**Issue by webappzero** [magomimmo/modern-cljs#435]
An ```out``` dir is generated in the project's root directory at the time of visiting ```localhost:3000```, after executing ```(start-repl)``` within Tutorial 2. I can't find an explanation for this in the tutorial or online. I see it only includes clj, cljs & goog related dirs. I assume these are needed by ```boot-cljs-repl```. 

Am I close? Any additional helpful explanation? Should we include an explanation in Tutorial 2?

**Comment by GiovanniFerrari** [comment]
Hi Jay!

I have briefly take a look to "start-repl" code, which simply call "cemerick.piggieback/cljs-repl" function. This function is from "https://github.com/cemerick/piggieback". In the readme.md of this library, section "Usage" it says that all files from the cljs compiler are written by default in an "out" directory. I'm not sure, but I think that every statements written in bREPL are compiled and written in this directory :thinking:

**Comment by webappzero** [comment]
Great sleuthing! That gives me a bread crumb trail to follow to learn more. Thanks Giovanni. I'll close this issue now that we know. The curious minded can now find this issue if they are digging that deep, unless you all want to add a note to the tutorial. My best : )
