### ISSUE TITLE
Tutorial 3: Where is :output-to configured?

### ISSUE THREAD

**Issue by webappzero** [magomimmo/modern-cljs#436]
In the **_Defaults overwriting_** section, the text states:

> If you take a look at the clojurescript compiler options you'll discover that you need two options to > be passed to the CLJS compiler to support this new files organization:
>
> :output-to: sets the path to the JavaScript file that will be output

But then, only ```:assest-path``` is directly configured by me. So is ```:output-to``` configured? Is this value inferred from GClosure? If so then the statement that "you need to configure two options" was misleading for me. What am I missing here?

**Comment by magomimmo** [comment]
Hi Jay, me and my team are on vacation at the moment. Some of them could be back for the end of augusts, other laters. Sorry about that. We'll be back in a couple of weeks or little more.

**Comment by webappzero** [comment]
No rush on my account. I greatly appreciate these freely available learning resources.

**Comment by GiovanniFerrari** [comment]
Hi Jay! 

As explained here: "https://github.com/boot-clj/boot-cljs/blob/master/docs/compiler-options.md", if the :output-to option is not specified by the user, boot-cljs use the relative path of the main.cljs.edn file.

**Comment by webappzero** [comment]
Hi Giovanni : )

Thank you, that makes sense now. **What are your thoughts on adding a blurb to that effect just after the text I cite in the first post?** 

Personally, I think it might be a good idea to be explicit about where this is getting configured for pedantic types, like me.

**Comment by GiovanniFerrari** [comment]
I think it's absolutely right, I'll do it right away ; ) thanks!
