### ISSUE TITLE
More consistent and descriptive commits

### ISSUE THREAD

**Issue by olivergeorge** [magomimmo/modern-cljs#96]
Hi Mimmo

Perhaps since you're showing best practice it's a good idea to tidy up your suggested git commands and git messages.  

Some thoughts below...

Since the tutorials do a pretty good job of focusing on one feature at a time I think the commits are pretty atomic.  No big issues here.

Descriptions start out good but further on they are "finished step 2" etc.  This is a pain when you type git log to find out what tutorial you're up to.

git commit -am makes me cringe for two reasons.  Firstly it doesn't encourage a review of changes so it's easy to commit experiments / testing etc by mistake.  Also it doesn't add new files so only updated files are committed.

I seem to recall some tutorials suggest branching commands without an explanation as to why.  Perhaps they are remnants from an older style.  (Or I could just be getting confused with the checkout commands for those loading up from your repo)

Thanks again for sharing these with us.

cheers, Oliver

**Comment by twiden** [comment]
I think that it would be helpful if the commit messages included the chapter number. For example 
`git commit -am "Ch 13. DRY while crossing the border"`

**Comment by magomimmo** [comment]
The first edition of the series is no more active/supported
